In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('HeartDisease.csv')
df

Unnamed: 0  Age  Sex            cp  trestbps  chol  fbs  restecg  \
0             1   63    1       typical       145   233    1        2   
1             2   67    1  asymptomatic       160   286    0        2   
2             3   67    1  asymptomatic       120   229    0        2   
3             4   37    1    nonanginal       130   250    0        0   
4             5   41    0    nontypical       130   204    0        2   
..          ...  ...  ...           ...       ...   ...  ...      ...   
298         299   45    1       typical       110   264    0        0   
299         300   68    1  asymptomatic       144   193    1        0   
300         301   57    1  asymptomatic       130   131    0        0   
301         302   57    0    nontypical       130   236    0        2   
302         303   38    1    nonanginal       138   175    0        0   

      thalach  exang  oldpeak  slope   ca        thal AHD(target)  
0         150      0      2.3      3  0.0       fixed          No  
1         108      1      1.5      2  3.0      normal         Yes  
2         129      1      2.6      2  2.0  reversable         Yes  
3         187      0      3.5      3  0.0      normal          No  
4         172      0      1.4      1  0.0      normal          No  
..        ...    ...      ...    ...  ...         ...         ...  
298       132      0      1.2      2  0.0  reversable         Yes  
299       141      0      3.4      2  2.0  reversable         Yes  
300       115      1      1.2      2  1.0  reversable         Yes  
301       174      0      0.0      2  1.0      normal         Yes  
302       173      0      0.0      1  NaN      normal          No  

[303 rows x 15 columns]

In [3]:
df['cp'] = df['cp'].astype('string')
df['thal'] = df['thal'].astype('string')
df['AHD(target)'] = df['AHD(target)'].astype('string')

In [4]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0  Age  Sex            cp  trestbps  chol  fbs  restecg  \
0             1   63    1       typical       145   233    1        2   
1             2   67    1  asymptomatic       160   286    0        2   
2             3   67    1  asymptomatic       120   229    0        2   
3             4   37    1    nonanginal       130   250    0        0   
4             5   41    0    nontypical       130   204    0        2   
..          ...  ...  ...           ...       ...   ...  ...      ...   
298         299   45    1       typical       110   264    0        0   
299         300   68    1  asymptomatic       144   193    1        0   
300         301   57    1  asymptomatic       130   131    0        0   
301         302   57    0    nontypical       130   236    0        2   
302         303   38    1    nonanginal       138   175    0        0   

      thalach  exang  oldpeak  slope   ca        thal AHD(target)  
0         150      0 

In [5]:
df.dtypes

Unnamed: 0       int64
Age              int64
Sex              int64
cp              string
trestbps         int64
chol             int64
fbs              int64
restecg          int64
 thalach         int64
exang            int64
oldpeak        float64
slope            int64
ca             float64
thal            string
AHD(target)     string
dtype: object

In [6]:
df['cp'] = df.cp.map({'typical': 0, 'asymptomatic': 1 ,'nonanginal': 2, 'nontypical': 3})
df['thal'] = df.thal.map({'normal': 3, 'fixed': 6 ,'reversable': 7})
df['AHD(target)'] = df['AHD(target)'].map({'No': 0, 'Yes': 1 })
df.head()

Unnamed: 0  Age  Sex  cp  trestbps  chol  fbs  restecg   thalach  exang  \
0           1   63    1   0       145   233    1        2       150      0   
1           2   67    1   1       160   286    0        2       108      1   
2           3   67    1   1       120   229    0        2       129      1   
3           4   37    1   2       130   250    0        0       187      0   
4           5   41    0   3       130   204    0        2       172      0   

   oldpeak  slope   ca  thal  AHD(target)  
0      2.3      3  0.0   6.0            0  
1      1.5      2  3.0   3.0            1  
2      2.6      2  2.0   7.0            1  
3      3.5      3  0.0   3.0            0  
4      1.4      1  0.0   3.0            0

In [7]:
df.dtypes

Unnamed: 0       int64
Age              int64
Sex              int64
cp               int64
trestbps         int64
chol             int64
fbs              int64
restecg          int64
 thalach         int64
exang            int64
oldpeak        float64
slope            int64
ca             float64
thal           float64
AHD(target)      int64
dtype: object

In [8]:
df = df.dropna()
df

Unnamed: 0  Age  Sex  cp  trestbps  chol  fbs  restecg   thalach  exang  \
0             1   63    1   0       145   233    1        2       150      0   
1             2   67    1   1       160   286    0        2       108      1   
2             3   67    1   1       120   229    0        2       129      1   
3             4   37    1   2       130   250    0        0       187      0   
4             5   41    0   3       130   204    0        2       172      0   
..          ...  ...  ...  ..       ...   ...  ...      ...       ...    ...   
297         298   57    0   1       140   241    0        0       123      1   
298         299   45    1   0       110   264    0        0       132      0   
299         300   68    1   1       144   193    1        0       141      0   
300         301   57    1   1       130   131    0        0       115      1   
301         302   57    0   3       130   236    0        2       174      0   

     oldpeak  slope   ca  thal  AHD(target)  
0        2.3      3  0.0   6.0            0  
1        1.5      2  3.0   3.0            1  
2        2.6      2  2.0   7.0            1  
3        3.5      3  0.0   3.0            0  
4        1.4      1  0.0   3.0            0  
..       ...    ...  ...   ...          ...  
297      0.2      2  0.0   7.0            1  
298      1.2      2  0.0   7.0            1  
299      3.4      2  2.0   7.0            1  
300      1.2      2  1.0   7.0            1  
301      0.0      2  1.0   3.0            1  

[297 rows x 15 columns]

In [9]:
X = np.asarray(df[['Age', 'Sex', 'cp', 'trestbps', 'chol', 'fbs','restecg' , 'exang' , 'oldpeak' ,'slope' , 'ca' , 'thal' ,' thalach' ]])
X[0:5]

array([[ 63. ,   1. ,   0. , 145. , 233. ,   1. ,   2. ,   0. ,   2.3,
          3. ,   0. ,   6. , 150. ],
       [ 67. ,   1. ,   1. , 160. , 286. ,   0. ,   2. ,   1. ,   1.5,
          2. ,   3. ,   3. , 108. ],
       [ 67. ,   1. ,   1. , 120. , 229. ,   0. ,   2. ,   1. ,   2.6,
          2. ,   2. ,   7. , 129. ],
       [ 37. ,   1. ,   2. , 130. , 250. ,   0. ,   0. ,   0. ,   3.5,
          3. ,   0. ,   3. , 187. ],
       [ 41. ,   0. ,   3. , 130. , 204. ,   0. ,   2. ,   0. ,   1.4,
          1. ,   0. ,   3. , 172. ]])

In [10]:
y = np.asarray(df['AHD(target)'])
y [0:5]

array([0, 1, 1, 0, 0], dtype=int64)

In [11]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.93618065,  0.69109474, -1.78837501,  0.75038004, -0.27644339,
         2.43042728,  1.01019851, -0.69641941,  1.06896529,  2.26414539,
        -0.72197605,  0.65587737,  0.01749443],
       [ 1.3789285 ,  0.69109474, -0.62101814,  1.59626645,  0.74455507,
        -0.41145029,  1.01019851,  1.43591632,  0.38177332,  0.6437811 ,
         2.47842525, -0.89422007, -1.81633388],
       [ 1.3789285 ,  0.69109474, -0.62101814, -0.65943064, -0.35349988,
        -0.41145029,  1.01019851,  1.43591632,  1.32666228,  0.6437811 ,
         1.41162482,  1.17257652, -0.89941972],
       [-1.94168041,  0.69109474,  0.54633874, -0.09550637,  0.05104668,
        -0.41145029, -1.00341866, -0.69641941,  2.09975324,  2.26414539,
        -0.72197605, -0.89422007,  1.63300986],
       [-1.49893255, -1.44697961,  1.71369562, -0.09550637, -0.83510292,
        -0.41145029,  1.01019851, -0.69641941,  0.29587432, -0.97658319,
        -0.72197605, -0.89422007,  0.97807117]])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (237, 13) (237,)
Test set: (60, 13) (60,)


In [13]:
from sklearn.naive_bayes import GaussianNB

In [14]:
nb = GaussianNB()
nb.fit(X_train,y_train)

GaussianNB()

In [15]:
print("Naive Bayes score: ",nb.score(X_test, y_test))

Naive Bayes score:  0.9333333333333333
